module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
]

module.exports.descriptions = [
    "Nestled amidst towering pines, our family-friendly campground offers spacious sites and endless outdoor activities",
    "Experience nature's tranquility at our secluded campground, surrounded by lush forests and babbling brooks",
    "Perfect for a weekend getaway, our scenic campground boasts stunning mountain vistas and star-filled skies",
    "Bring the whole family to our lakeside campground, where swimming, fishing, and campfire stories await",
    "Explore the wonders of the wilderness at our rustic campground, where adventure beckons around every corner",
    "Unwind in nature's embrace at our riverside campground, where the soothing sounds of flowing water provide the soundtrack to your escape",
    "Discover the beauty of the great outdoors at our dog-friendly campground, where furry companions are welcomed with open arms",
    "Escape the hustle and bustle of city life at our peaceful campground, where serenity and relaxation are guaranteed",
    "Experience the magic of camping under the stars at our campground, where stargazing opportunities abound in the clear night sky",
    "Create memories to last a lifetime at our family-oriented campground, where laughter and togetherness are the essence of every adventure",
    "Immerse yourself in nature's beauty at our eco-friendly campground, where sustainability meets serenity",
    "Embark on a wilderness retreat at our backcountry campground, where rugged trails lead to hidden treasures",
    "Find your inner peace at our yoga-friendly campground, nestled in a tranquil valley with breathtaking sunrise views",
    "Unleash your adventurous spirit at our adrenaline-packed campground, offering zip-lining, rock climbing, and more",
    "Indulge in lakeside luxury at our glamping campground, where plush tents and gourmet dining redefine outdoor living",
    "Dive into aquatic adventures at our beachfront campground, where sun, sand, and surf await eager beachcombers",
    "Discover the charm of small-town camping at our quaint campground, just a stone's throw away from local shops and attractions",
    "Escape to a winter wonderland at our snow-capped campground, where cozy cabins and cross-country skiing await snow enthusiasts",
    "Connect with fellow travelers at our social campground, where communal fire pits and group activities foster friendships and fun",
    "Channel your inner cowboy at our Western-themed campground, where horseback riding and campfire cookouts evoke the spirit of the Wild West",
    "Experience the thrill of off-grid camping at our remote campground, where unspoiled landscapes and starry skies beckon true adventurers",
    "Treat yourself to a taste of luxury at our boutique campground, where spa treatments and gourmet cuisine redefine outdoor indulgence",
    "Escape the summer heat at our mountain retreat campground, where cool breezes and shaded trails provide respite from the sun",
    "Step back in time at our historic campground, where heritage cabins and guided tours offer a glimpse into the past",
    "Create lifelong memories at our multi-generational campground, where activities for all ages ensure fun for the whole family"
]